#!/bin/bash

set -e

DC="${DC:-exec}"

TTY=""
if [[ ! -t 1 ]]; then
  TTY="-T"
fi

function cmd {
  # Run any command in the php container.
  _dc php "${@}"
}

function composer {
  # Run Composer commands.
  DC=run
  cmd composer "${@}"
}

function help {
  printf "%s <task> [args]\n\nTasks:\n" "${0}"

  compgen -A function | grep -v "^_" | cat -n

  printf "\nExtended help:\n  Each task has comments for general usage\n"
}

function test:pest {
  # Run tests with Pest.
  DC=run
  cmd pest "${@}"
}

function test:phpunit {
  # Run tests with PHPUnit.
  DC=run
  cmd phpunit "${@}"
}

function _dc {
  docker-compose ${DC} ${TTY} "${@}"
}

eval "${@:-help}"
