FROM php:{{ @('php.version') }}-cli-alpine
ENV PATH=$PATH:/app/vendor/bin
COPY --from=composer /usr/bin/composer /usr/bin/composer
WORKDIR /app
COPY composer.json .
COPY composer.lock .
RUN composer validate --strict
RUN composer install
COPY . .
