name: CI

on:
  push:
    paths-ignore:
      - '*.md'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - run: docker-compose build
      - run: docker-compose run php php -v
      - run: docker-compose run php composer install
      - run: docker-compose run php phpunit --testdox --colors=always
