name: CI

on:
  push:
    paths-ignore:
      - '*.md'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout the code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
      -
        name: Build the containers
        run: docker build -t php-south-wales-katas .
      -
        name: Run tests
        run: docker run -t php-south-wales-katas phpunit --testdox --colors=always
