name: CI

on:
  push:
    paths-ignore:
      - '*.md'

env:
  artifact_dir: ~/artifacts
  artifact_name: docker-image
  docker_image_name: php-south-wales-katas
  docker_image_archive_name: docker-image.tar
  php_version: 7.4

jobs:
  build:
    name: Build the containers
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
      -
        uses: shivammathur/setup-php@36cb9fb0fccf887130d6c5a3d40a3b3479310026 # 2.12.0
        with:
          php-version: ${{ env.php_version }}
      -
        run: |
          curl --output ./ws --location https://github.com/my127/workspace/releases/download/0.1.3/ws
          chmod +x ws && sudo mv ws /usr/local/bin/ws
      -
        run: ws apply config
      -
        run: ws docker images build
      -
        run: mkdir ${{ env.artifact_dir }}
      -
        run: docker save ${{ env.docker_image_name }} > ${{ env.artifact_dir }}/${{ env.docker_image_archive_name }}
      -
        uses: actions/upload-artifact@27121b0bdffd731efa15d66772be8dc71245d074 # v2.2.4
        with:
          name: ${{ env.artifact_name }}
          path: ${{ env.artifact_dir }}
          retention-days: 1

  phpunit:
    name: Run PHPUnit tests
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      -
        uses: actions/download-artifact@3be87be14a055c47b01d3bd88f8fe02320a9bb60 # v2.0.10
        with:
          name: ${{ env.artifact_name }}
          path: ${{ env.artifact_dir }}
      -
        run: |
          cd ${{ env.artifact_dir }}
          docker load < ${{ env.docker_image_archive_name }}
      -
        run: docker run -t ${{ env.docker_image_name }} phpunit --testdox --colors=always
  pest:
    name: Run Pest tests
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      -
        uses: actions/download-artifact@3be87be14a055c47b01d3bd88f8fe02320a9bb60 # v2.0.10
        with:
          name: ${{ env.artifact_name }}
          path: ${{ env.artifact_dir }}
      -
        run: |
          cd ${{ env.artifact_dir }}
          docker load < ${{ env.docker_image_archive_name }}
      -
        run: docker run -t ${{ env.docker_image_name }} pest
