name: CI

on:
  push:
    paths-ignore:
      - '*.md'

jobs:
  build:
    name: Build the containers
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
      -
        run: docker build -t php-south-wales-katas .
      -
        run: mkdir ~/artifacts
      -
        run: docker save php-south-wales-katas > ~/artifacts/docker-image.tar
      -
        uses: actions/upload-artifact@27121b0bdffd731efa15d66772be8dc71245d074 # v2.2.4
        with:
          name: docker-image
          path: ~/artifacts
          retention-days: 1

  phpunit:
    name: Run PHPUnit tests
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      -
        uses: actions/download-artifact@3be87be14a055c47b01d3bd88f8fe02320a9bb60 # v2.0.10
        with:
          name: docker-image
          path: ~/artifacts
      -
        run: |
          cd ~/artifacts
          docker load < docker-image.tar
      -
        run: docker run -t php-south-wales-katas phpunit --testdox --colors=always

  pest:
    name: Run Pest tests
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      -
        uses: actions/download-artifact@3be87be14a055c47b01d3bd88f8fe02320a9bb60 # v2.0.10
        with:
          name: docker-image
          path: ~/artifacts
      -
        run: |
          cd ~/artifacts
          docker load < docker-image.tar
      -
        run: docker run -t php-south-wales-katas pest
