name: CI

on:
  push:
    paths-ignore:
      - '*.md'

env:
  artifact_dir: ~/artifacts
  artifact_name: docker-image
  docker_image_name: php-south-wales-katas
  docker_image_archive_name: docker-image.tar
  php_version: 7.4

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
      - run: docker-compose build
      - run: ./run composer install
      - run: ./run test:pest
